name: Update Yield Data Daily
on:
  schedule:
    - cron: '0 21 * * *'  # Daily at 9 AM UTC (2 AM MST, after market close)
  workflow_dispatch:  # Manual trigger
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install pandas requests
    - name: Fetch and update yield data
      run: python update_yield_data.py
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add yield_data_all.csv
        git diff --staged --quiet || git commit -m "Update yield data - $(date +%Y-%m-%d)"
        git push
